# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: env file building
      run: echo -e "${{ secrets.GO_ENV_FILE }}" > .env

    - name: Find and stop existing process
      run: |
        PID=$(pgrep -f "make run")
        if [ -n "$PID" ]; then
          echo "Stopping existing process with PID $PID"
          kill $PID
          sleep 2
        else
          echo "No existing process found"
        fi

    - name: Start new Process in the background
      run: make run
